image: Visual Studio 2015   # на этом VM-образе установлены все Visual Studio с 2008 по 2015

build_script:
    # скрипт сборки проекта:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%
    - cmake --build . %CMAKE_BUILD_FLAGS%

test_script:
    # скрипт тестирования проекта:
    - ctest -C %CONFIGURATION% --output-on-failure

